name: synonym_app
description: Synonym and Antonym brain training game.
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rive: ^0.6.8
  after_init: ^0.1.2
  toast: ^0.1.5
  progress_dialog: ^1.2.4
  firebase_storage: ^10.0.6
  shared_preferences: ^2.0.5
  image_cropper: ^1.4.0
  image_picker: ^0.7.3
  provider: ^5.0.0
  audioplayers: ^0.20.1
  assets_audio_player: ^3.0.3+3
  equatable: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  file_picker: ^3.0.0
  spreadsheet_decoder: ^2.0.0
  uuid: ^3.0.2
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  get: ^3.22.2
  sign_in_with_apple: ^3.0.0
  google_sign_in: ^5.0.1
  crypto: ^3.0.0
  flutter_native_splash: ^1.1.5+1
  google_fonts: ^2.1.0
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.jpeg"

flutter_native_splash:
  image: "assets/splash.png"
  color: "#ffffff"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/QuestionData.xlsx
    - assets/logo.png
    - assets/app_logo.jpeg
    - assets/splash.png
    - assets/header.png
    - assets/you_won.png
    - assets/SynAntL1.png
    - assets/SynAntL2.png
    - assets/SynAntL3.png
    - assets/hourglass_icon.png
    - assets/bomb_icon.png
    - assets/clock_icon.png
#    - assets/arrow_left_blue.png
#    - assets/arrow_right_red.png
    - assets/arrow_left_blue.png
    - assets/arrow_right_blue.png
    - assets/arrow_left_red.png
    - assets/arrow_right_red.png
    - assets/right.png
    - assets/wrong.png
    - assets/facebooklogo.png
    - assets/applelogo.png
    - assets/googlelogo.png
    - assets/backgroundsong1.mp3
    - assets/Sound_Correct.wav
    - assets/Sound_Wrong.wav

  fonts:
    - family: Retro
      fonts:
        - asset: fonts/Retro.ttf