name: synonym_app
description: A new Flutter application.
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  rive: ^0.5.1
  after_init: ^0.1.2
  toast: ^0.1.5
  progress_dialog: ^1.2.4
  firebase_storage:
  shared_preferences: ^0.5.10
  image_cropper: ^1.3.0
  image_picker: ^0.6.7+17
  provider: ^4.3.2+1
  audioplayers: ^0.17.0
  equatable: ^1.2.4
  admob_flutter: ^0.3.4
  flutter_launcher_icons: ^0.7.5
  file_picker: ^1.13.3
  spreadsheet_decoder: ^1.2.0
  uuid: ^2.2.2
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.3
  get: ^3.22.2
  flutter_facebook_login: ^3.0.0
  sign_in_with_apple: ^2.5.4
  google_sign_in: ^4.5.6
  crypto: ^2.1.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.jpeg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - animations/splash_anim.flr

    - assets/splash.png
    - assets/logo.png
    - assets/app_logo.jpeg
    - assets/you_won.png
    - assets/SynAntL1.png
    - assets/SynAntL2.png
    - assets/SynAntL3.png
#    - assets/arrow_left_blue.png
#    - assets/arrow_right_red.png
    - assets/arrow_left_blue.png
    - assets/arrow_right_blue.png
    - assets/arrow_left_red.png
    - assets/arrow_right_red.png
    - assets/right.png
    - assets/wrong.png
    - assets/facebooklogo.png
    - assets/applelogo.png
    - assets/googlelogo.png

#    - assets/blue_pause.png
#    - assets/blue_go_back.png
#    - assets/red_pause.png
#    - assets/red_go_back.png
#
#    - assets/blue_arrow_left.png
#    - assets/blue_arrow_right.png
#    - assets/red_arrow_left.png
#    - assets/red_arrow_right.png
#
#    - assets/home_logo.png
#    - assets/background.png
#    - assets/fb_logo.png
#    - assets/twitter_logo.png
#    - assets/base_circle.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Retro
      fonts:
        - asset: fonts/Retro.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
